// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dao

import (
	"time"
)

type ActiveIntegration struct {
	ID               int32
	AccountID        int32
	ExtCompanyID     string
	CompanyName      string
	ConfirmationTime time.Time
}
