// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package dao

import (
	"context"
	"time"
)

const createActiveIntegration = `-- name: CreateActiveIntegration :one
INSERT INTO active_integrations (
  account_id, ext_company_id, company_name, confirmation_time
) VALUES (
  $1, $2, $3, $4
)
 RETURNING id
`

type CreateActiveIntegrationParams struct {
	AccountID        int32
	ExtCompanyID     string
	CompanyName      string
	ConfirmationTime time.Time
}

func (q *Queries) CreateActiveIntegration(ctx context.Context, arg CreateActiveIntegrationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createActiveIntegration,
		arg.AccountID,
		arg.ExtCompanyID,
		arg.CompanyName,
		arg.ConfirmationTime,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getActiveIntegration = `-- name: GetActiveIntegration :one
SELECT id, account_id, ext_company_id, company_name, confirmation_time FROM active_integrations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetActiveIntegration(ctx context.Context, id int32) (ActiveIntegration, error) {
	row := q.db.QueryRowContext(ctx, getActiveIntegration, id)
	var i ActiveIntegration
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExtCompanyID,
		&i.CompanyName,
		&i.ConfirmationTime,
	)
	return i, err
}
